package com.qq.modules.td.logic.bt_ai
{
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_BubbleFlower;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_Garlic;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_HighWallnut;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_IcePea;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_Nitration_Mushroom;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_Nuts;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_OxygenAlgae;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_PrismGrass;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_Qlossy_Ganoderma;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_ThunderPine;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_bambooLi;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_banana;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_blover;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_bowling;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_bowlingBomb;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_carrotRocket;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_cherryBomb;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_citron;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_coconutCannon;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_daffodil;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_dandelion;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_durian;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_empeach;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_flytrap;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_hayrick;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_icebean;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_jalapeno;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_kernalpult;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_laserbean;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_moteng;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_nitreShroom;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_peaShooter;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_pineapple;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_pomegranate;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_snapdragon;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_spikeweed;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_springBean;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_squash;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_sunFlower;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_threepeater;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_tileTurnip;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_waxgourd;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.plant.AI_plant_wintermelon;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Arsonist;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_BarrelRoller;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Bengbu;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Bug_Bot_Imp;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Emperor_Qin;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Emperor_Qin_Guide;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Future_Jetpack;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Future_Protector;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Future_Zomboss;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Gargantuar;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Gunman;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Harvester;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Mech_Disco;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Mech_Football;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Mech_Gargantuar;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_MiniGameSeagull;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Monkey;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_MonkeyCharmer;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Pirate_Cannon;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Pirate_Captain;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Pirate_CaptainParrot;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Pirate_Zomboss;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Poison;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Qin_Archer;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Qin_Drunkard;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Qin_Normal;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Qin_Peddler;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Quicksand;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Supervisor;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Swashbuckler;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Terracotta;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Wolf_Knight;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Yaksha;
   import com.qq.modules.td.logic.bt_ai.aiNode.aiCode.zombie.AI_Zombie_Yeti;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeBalloonPop;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeCatchSun;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeCatchSunEnd;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeCoolDown;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeCustomProp;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeDie;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeDoAction;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeEat;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeFly;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeFrozenAI;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeGasp;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeIdle;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeJumpFail;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeJumpSuccess;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeNomalWalk;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeRun;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeSmash;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeSwitcherIdle;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.ExeSwitcherRun;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExeCharmZombie;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExeCherryBombExplode;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExeFadeOutPlant;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExeLuckygrassAttack;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExeMagnetIronArmor;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExePlantAttack;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExePlantIdle;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExePlantProtect;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.plant.ExePlantResetDuration;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.zombie.ExeFirePlant;
   import com.qq.modules.td.logic.bt_ai.aiNode.executeNode.zombie.ExeZombieResetDuration;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqArmorValid;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqAttackTarget;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqAttackTargetCatalog;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqAttackZombieCanJump;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqCoolDown;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqCustomProp;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqDisapperTimeout;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqExplororFireAttackTarget;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasFire;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasIronArmor;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasNoOtherZombieCatchingSun;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasShootZombie;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasSunInScreen;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasUnswitchedZombieInRange;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqHasZombieInAttackRange;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqIceburgHasTargetInAttackRange;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqIsFlying;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqJustCatchingSun;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqMeetTombCondition;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqNotMaxHP;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqNotState;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqPlantCurAction;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqPlantDurationExpire;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqSelfHP;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqSelfJump;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqZombieCurAction;
   import com.qq.modules.td.logic.bt_ai.aiNode.requireNode.ReqZombieDurationExpire;
   import tencent.tools.behaviourTrees.BehaviourTreeCenter;
   
   public class AINodeConstant
   {
       
      
      public function AINodeConstant()
      {
         super();
         this.initAIConfig();
         this.registerAIClass();
      }
      
      private function initAIConfig() : void
      {
         BehaviourTreeCenter.instance.initAITreeConfig(AIFileConstant.ai_config);
      }
      
      private function registerAIClass() : void
      {
         BehaviourTreeCenter.instance.addClassRegister("ReqAttackTarget",ReqAttackTarget);
         BehaviourTreeCenter.instance.addClassRegister("ReqSelfHP",ReqSelfHP);
         BehaviourTreeCenter.instance.addClassRegister("ReqAttackZombieCanJump",ReqAttackZombieCanJump);
         BehaviourTreeCenter.instance.addClassRegister("ReqAttackTargetCatalog",ReqAttackTargetCatalog);
         BehaviourTreeCenter.instance.addClassRegister("ReqSelfJump",ReqSelfJump);
         BehaviourTreeCenter.instance.addClassRegister("ExeDie",ExeDie);
         BehaviourTreeCenter.instance.addClassRegister("ExeEat",ExeEat);
         BehaviourTreeCenter.instance.addClassRegister("ExeIdle",ExeIdle);
         BehaviourTreeCenter.instance.addClassRegister("ExeJumpFail",ExeJumpFail);
         BehaviourTreeCenter.instance.addClassRegister("ExeJumpSuccess",ExeJumpSuccess);
         BehaviourTreeCenter.instance.addClassRegister("ExeNomalWalk",ExeNomalWalk);
         BehaviourTreeCenter.instance.addClassRegister("ExeGasp",ExeGasp);
         BehaviourTreeCenter.instance.addClassRegister("ExeRun",ExeRun);
         BehaviourTreeCenter.instance.addClassRegister("ReqIsFlying",ReqIsFlying);
         BehaviourTreeCenter.instance.addClassRegister("ExeFly",ExeFly);
         BehaviourTreeCenter.instance.addClassRegister("ExeBalloonPop",ExeBalloonPop);
         BehaviourTreeCenter.instance.addClassRegister("ReqNotMaxHP",ReqNotMaxHP);
         BehaviourTreeCenter.instance.addClassRegister("ExeSmash",ExeSmash);
         BehaviourTreeCenter.instance.addClassRegister("ExeFrozenAI",ExeFrozenAI);
         BehaviourTreeCenter.instance.addClassRegister("ReqPlantDurationExpire",ReqPlantDurationExpire);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasShootZombie",ReqHasShootZombie);
         BehaviourTreeCenter.instance.addClassRegister("ExePlantResetDuration",ExePlantResetDuration);
         BehaviourTreeCenter.instance.addClassRegister("ExeLuckygrassAttack",ExeLuckygrassAttack);
         BehaviourTreeCenter.instance.addClassRegister("ExeMagnetIronArmor",ExeMagnetIronArmor);
         BehaviourTreeCenter.instance.addClassRegister("ReqDisapperTimeout",ReqDisapperTimeout);
         BehaviourTreeCenter.instance.addClassRegister("ExeFadeOutPlant",ExeFadeOutPlant);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasIronArmor",ReqHasIronArmor);
         BehaviourTreeCenter.instance.addClassRegister("ExeCherryBombExplode",ExeCherryBombExplode);
         BehaviourTreeCenter.instance.addClassRegister("ReqNotState",ReqNotState);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasZombieInAttackRange",ReqHasZombieInAttackRange);
         BehaviourTreeCenter.instance.addClassRegister("ReqIceburgHasTargetInAttackRange",ReqIceburgHasTargetInAttackRange);
         BehaviourTreeCenter.instance.addClassRegister("ExePlantProtect",ExePlantProtect);
         BehaviourTreeCenter.instance.addClassRegister("ExeZombieResetDuration",ExeZombieResetDuration);
         BehaviourTreeCenter.instance.addClassRegister("ExeCatchSun",ExeCatchSun);
         BehaviourTreeCenter.instance.addClassRegister("ExeCatchSunEnd",ExeCatchSunEnd);
         BehaviourTreeCenter.instance.addClassRegister("ReqJustCatchingSun",ReqJustCatchingSun);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasSunInScreen",ReqHasSunInScreen);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasNoOtherZombieCatchingSun",ReqHasNoOtherZombieCatchingSun);
         BehaviourTreeCenter.instance.addClassRegister("ReqArmorValid",ReqArmorValid);
         BehaviourTreeCenter.instance.addClassRegister("ReqCustomProp",ReqCustomProp);
         BehaviourTreeCenter.instance.addClassRegister("ReqZombieDurationExpire",ReqZombieDurationExpire);
         BehaviourTreeCenter.instance.addClassRegister("ReqMeetTombCondition",ReqMeetTombCondition);
         BehaviourTreeCenter.instance.addClassRegister("ExeCharmZombie",ExeCharmZombie);
         BehaviourTreeCenter.instance.addClassRegister("ReqCoolDown",ReqCoolDown);
         BehaviourTreeCenter.instance.addClassRegister("ExeCoolDown",ExeCoolDown);
         BehaviourTreeCenter.instance.addClassRegister("ReqPlantCurAction",ReqPlantCurAction);
         BehaviourTreeCenter.instance.addClassRegister("ReqZombieCurAction",ReqZombieCurAction);
         BehaviourTreeCenter.instance.addClassRegister("ExePlantIdle",ExePlantIdle);
         BehaviourTreeCenter.instance.addClassRegister("ExePlantAttack",ExePlantAttack);
         BehaviourTreeCenter.instance.addClassRegister("ExeSwitcherIdle",ExeSwitcherIdle);
         BehaviourTreeCenter.instance.addClassRegister("ExeSwitcherRun",ExeSwitcherRun);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasUnswitchedZombieInRange",ReqHasUnswitchedZombieInRange);
         BehaviourTreeCenter.instance.addClassRegister("ReqHasFire",ReqHasFire);
         BehaviourTreeCenter.instance.addClassRegister("ReqExplororFireAttackTarget",ReqExplororFireAttackTarget);
         BehaviourTreeCenter.instance.addClassRegister("ExeFirePlant",ExeFirePlant);
         BehaviourTreeCenter.instance.addClassRegister("ExeCustomProp",ExeCustomProp);
         BehaviourTreeCenter.instance.addClassRegister("ExeDoAction",ExeDoAction);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_peaShooter",AI_plant_peaShooter);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_moteng",AI_plant_moteng);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_bambooLi",AI_plant_bambooLi);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_dandelion",AI_plant_dandelion);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_sunFlower",AI_plant_sunFlower);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_carrotRocket",AI_plant_carrotRocket);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_waxgourd",AI_plant_waxgourd);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_flytrap",AI_plant_flytrap);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_squash",AI_plant_squash);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_hayrick",AI_plant_hayrick);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_bowling",AI_plant_bowling);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_bowlingBomb",AI_plant_bowlingBomb);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_snapdragon",AI_plant_snapdragon);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_kernalpult",AI_plant_kernalpult);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_spikeweed",AI_plant_spikeweed);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_springBean",AI_plant_springBean);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_threepeater",AI_plant_threepeater);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_coconutCannon",AI_plant_coconutCannon);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_pomegranate",AI_plant_pomegranate);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_daffodil",AI_plant_daffodil);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_durian",AI_plant_durian);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_pineapple",AI_plant_pineapple);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_cherryBomb",AI_plant_cherryBomb);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_jalapeno",AI_plant_jalapeno);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_icebean",AI_plant_icebean);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_wintermelon",AI_plant_wintermelon);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_laserbean",AI_plant_laserbean);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_blover",AI_plant_blover);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_citron",AI_plant_citron);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_empeach",AI_plant_empeach);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_nitreShroom",AI_plant_nitreShroom);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_tileTurnip",AI_plant_tileTurnip);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_glossy_ganoderma",AI_plant_Qlossy_Ganoderma);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_banana",AI_plant_banana);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_nitration_mushroom",AI_plant_Nitration_Mushroom);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_nuts",AI_plant_Nuts);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_highWallnut",AI_plant_HighWallnut);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_prismgrass",AI_plant_PrismGrass);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_oxygen_algae",AI_plant_OxygenAlgae);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_garlic",AI_plant_Garlic);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_thunderPine",AI_plant_ThunderPine);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_bubbleFlower",AI_plant_BubbleFlower);
         BehaviourTreeCenter.instance.addClassRegister("ai_plant_icepea",AI_plant_IcePea);
         BehaviourTreeCenter.instance.addClassRegister("ai_Zombie_Qin_Normal",AI_Zombie_Qin_Normal);
         BehaviourTreeCenter.instance.addClassRegister("ai_Zombie_Qin_Archer",AI_Zombie_Qin_Archer);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_qin_peddler",AI_Zombie_Qin_Peddler);
         BehaviourTreeCenter.instance.addClassRegister("ai_emperor_qin",AI_Zombie_Emperor_Qin);
         BehaviourTreeCenter.instance.addClassRegister("ai_emperor_qin_guide",AI_Zombie_Emperor_Qin_Guide);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_terracotta",AI_Zombie_Terracotta);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_drunkard",AI_Zombie_Qin_Drunkard);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_quicksand",AI_Zombie_Quicksand);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_supervisor",AI_Zombie_Supervisor);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_swashbuckler",AI_Zombie_Swashbuckler);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_pirate_captain",AI_Zombie_Pirate_Captain);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_pirate_captain_parrot",AI_Zombie_Pirate_CaptainParrot);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_gargantuar",AI_Zombie_Gargantuar);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_barrel_roller",AI_Zombie_BarrelRoller);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_monkeyCharmer",AI_Zombie_MonkeyCharmer);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_monkey",AI_Zombie_Monkey);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_miniGameSeagull",AI_Zombie_MiniGameSeagull);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_arsonist",AI_Zombie_Arsonist);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_gunman",AI_Zombie_Gunman);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_yeti",AI_Zombie_Yeti);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_priate_zomboss",AI_Zombie_Pirate_Zomboss);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_bug_bot_imp",AI_Zombie_Bug_Bot_Imp);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_future_protector",AI_Zombie_Future_Protector);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_future_jetpack",AI_Zombie_Future_Jetpack);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_mech_disco",AI_Zombie_Mech_Disco);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_mech_football",AI_Zombie_Mech_Football);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_poison",AI_Zombie_Poison);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_wolf_knight",AI_Zombie_Wolf_Knight);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_mech_gargantuar",AI_Zombie_Mech_Gargantuar);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_harvester",AI_Zombie_Harvester);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_future_zomboss",AI_Zombie_Future_Zomboss);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_pirate_cannon",AI_Zombie_Pirate_Cannon);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_bengbu",AI_Zombie_Bengbu);
         BehaviourTreeCenter.instance.addClassRegister("ai_zombie_yaksha",AI_Zombie_Yaksha);
      }
   }
}
